env: "local"
storage_path: "postgres://root:pass@localhost:5432/instant_messenger_db?sslmode=disable"
grpc:
  port: 50053
  timeout: 10h  
server: "http://localhost:8083"
lb_address: ":3002"
health_check_interval: 15s  