name: Unpacking .zip on Windows

on:
  push:
    paths:
      - '*.zip'  

jobs:
  unpack:
    runs-on: windows-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  

      - name: Unpacking .zip
        shell: pwsh
        run: |
          Expand-Archive -Path *.zip -DestinationPath .
        if: contains(github.event.head_commit.message, '.zip')

      - name: Commit and push changes
        shell: pwsh  
        run: |
          git config --global user.name 'mgrankin-cloud'
          git config --global user.email 'mgrankin272@gmail.com'
          git add . 
          git commit -m ".zip unpacked"  
          git push  